### ISSUE TITLE
Please add warning on README - Python 3.7 breaks Linux Mint

### ISSUE THREAD

**Issue by Mayccoll** [marblexu/PythonPlantsVsZombies#10]
Hi,
I'm not sure about other distributions, but Python 3.7 break Linux Mint. To fix it you have to go back to Python 3.6 and it's pretty wasteful.
A little warning wouldn't hurt.
Thank you

**Comment by marblexu** [comment]
If Linux Mint has a preinstalled lower version python (e.g. python 3.6), I think Linux Mint requires this specific version python. You can install another python 3.7 instead of updating python 3.6 to python 3.7 directly. Anyway, I'll add a notice on README.
