### ISSUE TITLE
建议加上音乐。

### ISSUE THREAD

**Issue by YuanQingLe** [marblexu/PythonPlantsVsZombies#16]
我用笔记本的触控板手忙脚乱地玩了一局之后，可能患了一种叫无声恐惧症的病:D迅速去网易云放了首歌听还好一点。因为玩的时候会非常想听到原版游戏那些熟悉的音效，但是啥也听不到，就感觉很恐怖。（好吧，有些夸张了，我没有恶意，就是希望能有个音乐就更好玩了。）

**Comment by marblexu** [comment]
pygame 对音乐的支持不太好，我有测试过在有些操作系统上，音乐文件会加载失败，导致游戏没法运行，所以目前不增加音乐。
